package Vista;

import javax.swing.table.DefaultTableModel;

public class ConsPacienteInternalFrame extends javax.swing.JInternalFrame {
    
    private Controlador.GestorPacienteControl gestorpacientesControl;
    private DefaultTableModel tabla;

    public ConsPacienteInternalFrame() {
        
        initComponents();
        gestorpacientesControl = new Controlador.GestorPacienteControl(this);
        String titulosTabla[] = {"Identificacion", "Nombres", "Apellidos", "Fecha Nac", "Sexo"};
        tabla = new DefaultTableModel(null, titulosTabla);
        ResultadosTbl.setModel(tabla);
        AceptarBtn.addActionListener(gestorpacientesControl);//
    }
    
    public DefaultTableModel getTableModel() {
        
        return tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        IdentificacionOpt = new javax.swing.JRadioButton();
        NombresOpt = new javax.swing.JRadioButton();
        ApellidosOpt = new javax.swing.JRadioButton();
        SexoOpt = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        ValorTxt = new javax.swing.JTextField();
        AceptarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResultadosTbl = new javax.swing.JTable();

        setTitle("Consulta de Pacientes");

        buttonGroup2.add(IdentificacionOpt);
        IdentificacionOpt.setText("Identificacion");

        buttonGroup2.add(NombresOpt);
        NombresOpt.setText("Nombres");

        buttonGroup2.add(ApellidosOpt);
        ApellidosOpt.setText("Apellidos");

        buttonGroup2.add(SexoOpt);
        SexoOpt.setText("Sexo");

        jLabel1.setText("Valor a Buscar");

        ValorTxt.setName("ValorTxt"); // NOI18N

        AceptarBtn.setText("Aceptar");
        AceptarBtn.setName("AceptarBtn"); // NOI18N

        ResultadosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ResultadosTbl.setName("ResultadosTbl"); // NOI18N
        jScrollPane2.setViewportView(ResultadosTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IdentificacionOpt)
                        .addGap(14, 14, 14)
                        .addComponent(NombresOpt)
                        .addGap(18, 18, 18)
                        .addComponent(ApellidosOpt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ValorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SexoOpt)
                    .addComponent(AceptarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdentificacionOpt)
                    .addComponent(NombresOpt)
                    .addComponent(ApellidosOpt)
                    .addComponent(SexoOpt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ValorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AceptarBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AceptarBtn;
    public javax.swing.JRadioButton ApellidosOpt;
    public javax.swing.JRadioButton IdentificacionOpt;
    public javax.swing.JRadioButton NombresOpt;
    public javax.swing.JTable ResultadosTbl;
    public javax.swing.JRadioButton SexoOpt;
    public javax.swing.JTextField ValorTxt;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}


